#!/bin/sh

. /opt/etc/openssl/vars

# list revoked certificates

CRL="${1:-${_CRLCERT}}"

if [ "$KEY_DIR" ]; then
    cd ${SSLROOT} &&
	$OPENSSL crl -text -noout -in $CRL
else
    echo 'Please source the vars script first (i.e. "source ./vars")'
    echo 'Make sure you have edited it to reflect your configuration.'
fi
